### ISSUE TITLE
sbn 자체를 받는 콜백 함수 추가

### ISSUE THREAD

**Issue by command0929** [jisungbin/MessengerReplyBot#3]
```typescript
function onNotification(event: Event) {
  if(event.packageName == "com.kakao.talk") {
    console.log("KakaoTalk Noti");
  }
}
```

그저 모든 알림에 반응하는 함수일 뿐...?

**Comment by command0929** [comment]
이런 함수가 있었으면 좋겠어요 !

**Comment by jisungbin** [comment]
@command0929 안녕하세요, 제안 감사합니다.

각 서비스마다 모두 동일한 알림 구조를 갖는다고 보장할 수 없기에, 현재로서는 엔진과 무관하게 모든 서비스를 지원하는 건 어렵습니다. 만약 특정 서비스의 지원 추가를 원하신다면 이에 맞는 엔진을 개발하여 PR을 올려주세요. 매우 긍정적으로 검토하겠습니다.

**Comment by command0929** [comment]
알겠습니당 :>
